src/Entity/Core/InscriptionHBAC/CertificatMedical.php
<?php

namespace App\Entity\Core;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Image
 *
 * @ORM\Table(name="core_inscription_certificat")
 * @ORM\Entity(repositoryClass="App\Repository\Core\CertificatMedicalRepository")
 * @ORM\HasLifecycleCallbacks()
 */
 class Certificat
 {
     /**
      * @var integer
      *
      * @ORM\Column(name="id", type="integer")
      * @ORM\Id
      * @ORM\GeneratedValue(strategy="AUTO")
      */
     private $id;

     /**
      * @ORM\Column(name="url", type="string", length=255)
      */
     private $url;

     /**
      * @ORM\Column(name="alt", type="string", length=255)
      */
     private $alt;

     /**
      * @var \DateTime
      * @Gedmo\Timestampable(on="create")
      * @ORM\Column(name="created_At", type="datetime", nullable=true)
      */
     private $createdAt;

     /**
      * @var \DateTime
      * @Gedmo\Timestampable(on="update")
      * @ORM\Column(name="updated_at",type="datetime", nullable=true)
      */
     private $updatedAt;

     /**
      * @var string $createdBy
      * @Gedmo\Blameable(on="create")
      * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateurs\User")
      * @ORM\JoinColumn(referencedColumnName="id")
      */
     private $createdBy;

     /**
      * @var string $updatedBy
      * @Gedmo\Blameable(on="update")
      * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateurs\User")
      * @ORM\JoinColumn(referencedColumnName="id")
      */
     private $updatedBy;

     private $file;

     // On ajoute cet attribut pour y stocker temporairement le nom du fichier
     private $tempFilename;


     // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
     public function setFile(UploadedFile $file)
     {
         $this->file = $file;
         // On vérifie si on avait déjà un fichier pour cette entité
         if (null !== $this->url) {
             // On sauvegarde l'extension du fichier pour le supprimer plus tard
             $this->tempFilename = $this->url;
             // On réinitialise les valeurs des attributs url et name
             $this->url = null;
             $this->alt = null;
         }
     }

     /**
      * @ORM\PrePersist()
      * @ORM\PreUpdate()
      */
     public function preUpload()
     {
         // Si jamais il n'y a pas de fichier (champ facultatif)
         if (null === $this->file) {
             return;
         }
         // Le nom du fichier est son id, on doit juste stocker également son extension
         // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
         $this->url = $this->file->guessExtension();
         // Et on génère l'attribut name de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
         $this->alt = $this->file->getClientOriginalName();
     }

     /**
      * @ORM\PostPersist()
      * @ORM\PostUpdate()
      */
     public function upload()
     {
         // Si jamais il n'y a pas de fichier (champ facultatif)
         if (null === $this->file) {
             return;
         }
         // Si on avait un ancien fichier, on le supprime
         if (null !== $this->tempFilename) {
             $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
             if (file_exists($oldFile)) {
                 unlink($oldFile);
             }
         }
         // On déplace le fichier envoyé dans le répertoire de notre choix
         $this->file->move(
             $this->getUploadRootDir(), // Le répertoire de destination
             $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
         );
     }

     /**
      * @ORM\PreRemove()
      */
     public function preRemoveUpload()
     {
         // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
         $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
     }

     /**
      * @ORM\PostRemove()
      */
     public function removeUpload()
     {
         // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
         if (file_exists($this->tempFilename)) {
             // On supprime le fichier
             unlink($this->tempFilename);
         }
     }

     protected function getUploadRootDir()
     {
         // On retourne le chemin relatif vers l'image pour notre code PHP
         return $this->getUploadDir();
     }

     public function getUploadDir()
     {
         // On retourne le chemin relatif vers l'image pour un navigateur
         return 'uploads/licences/certificats';
     }

     public function getWebPath()
     {
         return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
     }

     /**
      * Get id
      *
      * @return integer
      */
     public function getId()
     {
         return $this->id;
     }
     /**
      * Set url
      *
      * @param string $url
      *
      * @return Certificat
      */
     public function setUrl($url)
     {
         $this->url = $url;
         return $this;
     }
     /**
      * Get url
      *
      * @return string
      */
     public function getUrl()
     {
         return $this->url;
     }

     /**
      * Set name
      *
      * @param string $alt
      * @return Certificat
      */
     public function setAlt($alt)
     {
         $this->alt = $alt;
         return $this;
     }

     /**
      * Get alt
      *
      * @return string
      */
     public function getAlt()
     {
         return $this->alt;
     }

     public function getFile()
     {
         return $this->file;
     }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Certificat
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Certificat
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set createdBy
     *
     * @param \App\Entity\Utilisateurs\User $createdBy
     *
     * @return Certificat
     */
    public function setCreatedBy(\App\Entity\Utilisateurs\User $createdBy = null)
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return \App\Entity\Utilisateurs\User
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * Set updatedBy
     *
     * @param \App\Entity\Utilisateurs\User $updatedBy
     *
     * @return Certificat
     */
    public function setUpdatedBy(\App\Entity\Utilisateurs\User $updatedBy = null)
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /**
     * Get updatedBy
     *
     * @return \App\Entity\Utilisateurs\User
     */
    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }
}

src/Entity/Core/Licencie.php
<?php

namespace App\Entity\Core;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Licencie
 *
 * @ORM\Table(name="core_licencie")
 * @ORM\Entity(repositoryClass="App\Repository\Core\LicencieRepository")
 */
class Licencie
{
    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Core\ImgProfil", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true))
     */
    private $imgProfil;

    /**
     * Inverse Side
     * @ORM\ManyToMany(targetEntity="App\Entity\Core\Bureau\FicheBureau", mappedBy="licencies", orphanRemoval=true)
     */
    private $ficheBureau;

    /**
     * Inverse Side
     * @ORM\ManyToMany(targetEntity="App\Entity\Core\Entrainement", mappedBy="encadrants", orphanRemoval=true)
     */
    private $entrainements;

    /**
     * Inverse Side
     * @ORM\ManyToMany(targetEntity="App\Entity\Equipe\Equipe", mappedBy="entraineurs", orphanRemoval=true)
     */
    private $equipes;

    /**
     * Inverse Side
     * @ORM\ManyToMany(targetEntity="App\Entity\Equipe\Equipe", mappedBy="joueurs", orphanRemoval=true)
     */
    private $team;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Import\FichierLicencie", inversedBy="licencies", cascade={"persist"})
     * @ORM\JoinColumn(name="fichierLicencie_id", referencedColumnName="id")
     */
    private $fichierLicencie;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=75)
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=75)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="numeroLicence", type="string", length=255, nullable=true)
     */
    private $numeroLicence;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birthday", type="date", nullable=true)
     */
    private $birthday;

    /**
     * @var string
     *
     * @ORM\Column(name="mail", type="string", length=125, nullable=true)
     */
    private $mail;

    /**
     * @var string
     *
     * @ORM\Column(name="tel", type="string", length=50, nullable=true)
     */
    private $tel;

    /**
     * @var string
     *
     * @ORM\Column(name="portable", type="string", length=50, nullable=true)
     */
    private $portable;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_At", type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at",type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @var string $createdBy
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateurs\User")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @var string $updatedBy
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateurs\User")
     * @ORM\JoinColumn(referencedColumnName="id")
     */
    private $updatedBy;

    public function getPrenomNom()
    {
        return sprintf('%s  %s', $this->prenom, $this->nom);
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     *
     * @return Licencie
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Licencie
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set birthday
     *
     * @param \DateTime $birthday
     *
     * @return Licencie
     */
    public function setBirthday($birthday)
    {
        $this->birthday = $birthday;

        return $this;
    }

    /**
     * Get birthday
     *
     * @return \DateTime
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Set mail
     *
     * @param string $mail
     *
     * @return Licencie
     */
    public function setMail($mail)
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * Get mail
     *
     * @return string
     */
    public function getMail()
    {
        return $this->mail;
    }

    /**
     * Set tel
     *
     * @param string $tel
     *
     * @return Licencie
     */
    public function setTel($tel)
    {
        $this->tel = $tel;

        return $this;
    }

    /**
     * Get tel
     *
     * @return string
     */
    public function getTel()
    {
        return $this->tel;
    }

    /**
     * Set portable
     *
     * @param string $portable
     *
     * @return Licencie
     */
    public function setPortable($portable)
    {
        $this->portable = $portable;

        return $this;
    }

    /**
     * Get portable
     *
     * @return string
     */
    public function getPortable()
    {
        return $this->portable;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->equipes = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Licencie
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Licencie
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Add equipe
     *
     * @param \App\Entity\Equipe\Equipe $equipe
     *
     * @return Licencie
     */
    public function addEquipe(\App\Entity\Equipe\Equipe $equipe)
    {
        $this->equipes[] = $equipe;

        return $this;
    }

    /**
     * Remove equipe
     *
     * @param \App\Entity\Equipe\Equipe $equipe
     */
    public function removeEquipe(\App\Entity\Equipe\Equipe $equipe)
    {
        $this->equipes->removeElement($equipe);
    }

    /**
     * Get equipes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEquipes()
    {
        return $this->equipes;
    }

    /**
     * Set createdBy
     *
     * @param \App\Entity\Utilisateurs\User $createdBy
     *
     * @return Licencie
     */
    public function setCreatedBy(\App\Entity\Utilisateurs\User $createdBy = null)
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return \App\Entity\Utilisateurs\User
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * Set updatedBy
     *
     * @param \App\Entity\Utilisateurs\User $updatedBy
     *
     * @return Licencie
     */
    public function setUpdatedBy(\App\Entity\Utilisateurs\User $updatedBy = null)
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /**
     * Get updatedBy
     *
     * @return \App\Entity\Utilisateurs\User
     */
    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }

    /**
     * Set fichierLicencie
     *
     * @param \App\Entity\Import\FichierLicencie $fichierLicencie
     *
     * @return Licencie
     */
    public function setFichierLicencie(\App\Entity\Import\FichierLicencie $fichierLicencie = null)
    {
        $this->fichierLicencie = $fichierLicencie;

        return $this;
    }

    /**
     * Get fichierLicencie
     *
     * @return \App\Entity\Import\FichierLicencie
     */
    public function getFichierLicencie()
    {
        return $this->fichierLicencie;
    }


    /**
     * Set numeroLicence
     *
     * @param string $numeroLicence
     *
     * @return Licencie
     */
    public function setNumeroLicence($numeroLicence)
    {
        $this->numeroLicence = $numeroLicence;

        return $this;
    }

    /**
     * Get numeroLicence
     *
     * @return string
     */
    public function getNumeroLicence()
    {
        return $this->numeroLicence;
    }

    /**
     * Add entrainement
     *
     * @param \App\Entity\Core\Entrainement $entrainement
     *
     * @return Licencie
     */
    public function addEntrainement(\App\Entity\Core\Entrainement $entrainement)
    {
        $this->entrainements[] = $entrainement;

        return $this;
    }

    /**
     * Remove entrainement
     *
     * @param \App\Entity\Core\Entrainement $entrainement
     */
    public function removeEntrainement(\App\Entity\Core\Entrainement $entrainement)
    {
        $this->entrainements->removeElement($entrainement);
    }

    /**
     * Get entrainements
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEntrainements()
    {
        return $this->entrainements;
    }

    /**
     * Add team
     *
     * @param \App\Entity\Equipe\Equipe $team
     *
     * @return Licencie
     */
    public function addTeam(\App\Entity\Equipe\Equipe $team)
    {
        $this->team[] = $team;

        return $this;
    }

    /**
     * Remove team
     *

templates/inscriptionHBAC/newLicence.html.twig
{% extends 'layout.html.twig' %}

{% block titre %} Modifier mon Profil | {{ parent() }} {% endblock %}

{% block body %}

    <div class="row">
        <!-- Profile Sidebar -->
        <div class="col-lg-3 g-mb-50 g-mb-0--lg">
            <!-- User Image -->
            <div class="u-block-hover g-pos-rel">
                <figure>
                    {% if licencie.imgProfil %}
                    <img class="img-fluid w-100 u-block-hover__main--zoom-v1" src="{{ asset(licencie.imgProfil.webPath) }}" alt="Photo profil {{ licencie.prenomNom }}">
                    {% else %}
                        <img class="img-fluid w-100 u-block-hover__main--zoom-v1" src="{{ asset ('assets/frontend/img/user_no_img.png')}}" alt="Image Description">
                    {% endif %}
                </figure>

                <!-- User Info -->
                <span class="g-pos-abs g-top-20 g-left-0">
                  <a class="btn btn-sm u-btn-primary rounded-0" href="#!">{{ licencie.prenomNom }}</a>
                  <small class="d-block g-bg-black g-color-white g-pa-5">Handball</small>
                </span>
                <!-- End User Info -->
            </div>
            <!-- User Image -->
        </div>
        <!-- End Profile Sidebar -->

        <!-- Profle Content -->
        <div class="col-lg-9">
            <!-- Nav tabs -->
            <ul class="nav nav-justified u-nav-v1-1 u-nav-primary g-brd-bottom--md g-brd-bottom-2 g-brd-primary g-mb-20" role="tablist" data-target="nav-1-1-default-hor-left-underline" data-tabs-mobile-type="slide-up-down" data-btn-classes="btn btn-md btn-block rounded-0 u-btn-outline-primary g-mb-20">
                <li class="nav-item">
                    <a class="nav-link g-py-10 active" data-toggle="tab" href="#nav-1-1-default-hor-left-underline--1" role="tab">Edit Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link g-py-10" data-toggle="tab" href="#nav-1-1-default-hor-left-underline--2" role="tab"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link g-py-10" data-toggle="tab" href="#nav-1-1-default-hor-left-underline--3" role="tab"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link g-py-10" data-toggle="tab" href="#nav-1-1-default-hor-left-underline--4" role="tab"></a>
                </li>
            </ul>
            <!-- End Nav tabs -->

            <!-- Tab panes -->
            <div id="nav-1-1-default-hor-left-underline" class="tab-content">
                <!-- Edit Profile -->
                <div class="tab-pane fade show active" id="nav-1-1-default-hor-left-underline--1" role="tabpanel" data-parent="#nav-1-1-default-hor-left-underline">
                    <h2 class="h4 g-font-weight-300">Formulaire permettant de mettre à jour votre licence</h2>
                    <p>Merci de mettre une adresse mail valide pour recevoir par la suite l'email de fédération de Handball</p>

                    {{ form_errors(form) }}
                    {{ form_start(form, {'action': path('inscription_maj', {'id':licencie.id , 'prenom':licencie.prenom , 'nom':licencie.nom}), 'method': 'POST', 'attr' : {'class' : 'g-brd-around g-brd-gray-light-v4 g-pa-30 g-mb-30'} }) }}
                    <div class="form-group row g-mb-25">
                        <label class="col-sm-3 col-form-label g-mb-10"><i class="far fa-user"></i> {{ form_label(form.prenom) }}</label>
                        <div class="col-sm-9">
                            {{ form_widget(form.prenom) }}
                        </div>
                    </div>
                    <div class="form-group row g-mb-25">
                        <label class="col-sm-3 col-form-label g-mb-10"><i class="far fa-user"></i> {{ form_label(form.nom) }}</label>
                        <div class="col-sm-9">
                            {{ form_widget(form.nom) }}
                        </div>
                    </div>
                    <div class="form-group row g-mb-25">
                        <label class="col-sm-3 col-form-label g-mb-10"><i class="fas fa-birthday-cake"></i> {{ form_label(form.birthday) }}</label>
                        <div class="col-sm-9">
                            {{ form_widget(form.birthday) }}
                        </div>
                    </div>
                    <div class="form-group row g-mb-25">
                        <label class="col-sm-3 col-form-label g-mb-10"><i class="far fa-envelope"></i> {{ form_label(form.mail) }}</label>
                        <div class="col-sm-9">
                            {{ form_widget(form.mail) }}
                        </div>
                    </div>
                    <div class="form-group row g-mb-25">
                        <label class="col-sm-3 col-form-label g-mb-10"><i class="fas fa-phone"></i> {{ form_label(form.tel) }}</label>
                        <div class="col-sm-9">
                            {{ form_widget(form.tel) }}
                        </div>
                    </div>
                    <div class="form-group row g-mb-25">
                        <label class="col-sm-3 col-form-label g-mb-10"><i class="fas fa-mobile-alt"></i> {{ form_label(form.portable) }}</label>
                        <div class="col-sm-9">
                            {{ form_widget(form.portable) }}
                        </div>
                    </div>
                    <div class="form-group row g-mb-25">
                        <label class="col-sm-3 col-form-label g-mb-10"> {{ form_label(form.imgProfil) }}</label>
                        <div class="col-sm-9">
                            {{ form_widget(form.imgProfil) }}
                        </div>
                    </div>
                        {{ form_rest(form) }}
                    <div class="text-sm-right">
                        <a class="btn u-btn-darkgray rounded-0 g-py-12 g-px-25 g-mr-10" href="#!">Annuler</a>
                        <button class="btn u-btn-primary rounded-0 g-py-12 g-px-25" type="submit">Valider</button>
                    </div>
                    {{ form_end(form) }}
                </div>
                <!-- End Edit Profile -->
            </div>
            <!-- End Tab panes -->
        </div>
        <!-- End Profle Content -->
    </div>

{% endblock %}